import Header from "./component/Header"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header/>
        <hr></hr>
        {children}
        
        <hr></hr>
        <footer>test footer </footer>
        </body>
    </html>
  )
}
